package ng.com.bitsystems.mis.models.laboratories.bloodbank;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * BloodbankQueueLaboratoryInvestigations generated by hbm2java
 */

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ng.com.bitsystems.mis.models.BaseEntity;
import ng.com.bitsystems.mis.models.laboratories.LaboratoryInvestigations;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import java.util.HashSet;
import java.util.Set;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class InvestigationQueue extends BaseEntity {

     @OneToMany(cascade = CascadeType.ALL, mappedBy = "investigationQueue")
     private Set<LaboratoryInvestigations> laboratoryInvestigations=new HashSet<>();

     @OneToOne
     private DonationQueue donationQueue;
}


