package ng.com.bitsystems.mis.models.laboratories.bloodbank;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * BloodbankQueueLaboratoryInvestigations generated by hbm2java
 */

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ng.com.bitsystems.mis.models.BaseEntity;
import ng.com.bitsystems.mis.models.transactions.laboratory.LaboratoryTransaction;

import javax.persistence.Entity;
import javax.persistence.OneToOne;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class InvestigationQueue extends BaseEntity {

     @OneToOne
     private LaboratoryTransaction laboratoryTransaction;

     @OneToOne
     private DonationQueue donationQueue;
}


