package ng.com.bitsystems.mis.models.accounts.payments.insurance;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * InsuranceBloodbankTransaction generated by hbm2java
 */

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ng.com.bitsystems.mis.models.transactions.bloodbank.BloodbankTransaction;

import javax.persistence.Entity;
import javax.persistence.OneToOne;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class InsuredBloodbankTransactions extends InsuranceTransactions {

     @OneToOne
     private BloodbankTransaction bloodbankTransaction;
}


