INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Abdominal Aortic Aneurysm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Acanthamoeba Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('ACE (Adverse Childhood Experiences)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Acinetobacter Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Acquired Immune Deficiency Syndrome (AIDS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Acute Flaccid Myelitis (AFM)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Adenovirus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Adenovirus Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('ADHD [Attention Deficit/Hyperactivity Disorder]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Adult Vaccinations');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Adverse Childhood Experiences (ACE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('AFib, AF (Atrial fibrillation)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('AFM');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('African Trypanosomiasis ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('AHF (Alkhurma hemorrhagic fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('AIDS (Acquired Immune Deficiency Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Alkhurma hemorrhagic fever (AHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('ALS [Amyotrophic Lateral Sclerosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Alzheimer Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Amebiasis, Intestinal [Entamoeba histolytica infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('American Indian and Alaska Native Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('American Trypanosomiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Amphibians and Fish, Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Amyotrophic Lateral Sclerosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anaplasmosis, Human');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ancylostoma duodenale Infection, Necator americanus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Angiostrongylus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Animal-Related Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anisakiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anisakis Infection [Anisakiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anthrax Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anthrax [Bacillus anthracis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Antibiotic-resistant Infections - Listing');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Antibiotic and Antimicrobial Resistance Antibiotic Use');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Aortic Aneurysm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Aortic Dissection ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Arenavirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Arthritis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Childhood Arthritis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fibromyalgia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gout');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Osteoarthritis (OA)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rheumatoid Arthritis (RA)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ascariasis â€” see Ascaris Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ascaris Infection [Ascariasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Aseptic Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Aspergillosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Aspergillus Infection ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Asthma');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Atrial fibrillation (AFib, AF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Attention Deficit/Hyperactivity Disorder');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Autism');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Avian Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('B. cepacia infection (Burkholderia cepacia Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Babesia Infection â€” see Babesiosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Babesiosis [Babesia Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bacillus anthracis â€” see Anthrax');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bacillus anthracis Infection â€” see Anthrax');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Back Belts â€” see Ergonomic and Musculoskeletal Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bacterial Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Meningococcal Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bacterial Vaginosis (BV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Balamuthia Infection [Balamuthia mandrillaris Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Balamuthia mandrillaris Infection â€” see Balamuthia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Balantidiasis â€” see Balantidium Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Balantidium Infection [Balantidiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bartonella bacilliformis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bartonella henselae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bartonella Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CarriÃ³nâ€™s disease [Bartonella bacilliformis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cat Scratch Disease (CSD) [Bartonella henselae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trench fever [Bartonella quintana Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bartonella Quintana Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Baylisascaris Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('BCG (Tuberculosis Vaccine)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bilharzia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bioterrorism Agents/Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bird Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Birth Defects');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Black Lung [Coal Workers Pneumoconioses]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Blastocystis hominis Infection â€” see Blastocystis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Blastocystis Infection [Blastocystis hominis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Blastomycosis [Blastomyces dermatitidis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('blood clot');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Blood Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Body Lice [Pediculus humanus corporis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Borrelia burgdorferi Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Borreliosis, Louse-borne');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Borreliosis, Tick-borne');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Botulism [Clostridium botulinum Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bovine Spongiform Encephalopathy (BSE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Brainerd Diarrhea');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Breast and Ovarian Cancer and Family Health History');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Breast and Ovarian Cancer and Family Health History');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Breast Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also National Breast and Cervical Cancer Early Detection Program (NBCCEDP)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Breastfeeding');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bronchiolitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bronchitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Brucella Infection [Brucellosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Brucellosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('BSE (Bovine Spongiform Encephalopathy)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('BSE (Mad Cow Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bunyavirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Burkholderia cepacia Infection (B. cepacia infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Burkholderia mallei â€” see Glanders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Burkholderia pseudomallei Infection â€” see Melioidosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('BV (Bacterial Vaginosis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('B virus Infection [Herpes B virus]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('C. auris infection â€” see Candida auris infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('C. diff. Infection [Clostridium difficile Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('C. gattii cryptococcosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('C. neoformans cryptococcosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Campy (Campylobacter Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Campylobacter Infection (Campy) [Campylobacteriosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Campylobacteriosis â€” see Campylobacter Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Colorectal (Colon) Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gynecologic Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lung Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Prostate Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Skin Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cancer and Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Candida auris infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Canine Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Capillaria Infection [Capillariasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Capillariasis â€” see Capillaria Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Carbapenem-resistant Enterobacterales (CRE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Carbapenem resistant Klebsiella pneumonia (CRKP) â€” see Klebsiella pneumoniae');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cardiovascular Health â€” see Heart Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Carpal Tunnel Syndrome â€” see Ergonomic and Musculoskeletal Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Carrions disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cat Flea Tapeworm â€” see Tapeworm, Dog and Cat Flea');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cats, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cat Scratch Disease â€” see Bartonella henselae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cat Scratch Disease from Pets');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CCHF (Crimean-Congo hemorrhagic fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CDI (Chronic Disease Indicators)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cercarial Dermatitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cerebral Palsy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cervical Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also National Breast and Cervical Cancer Early Detection Program (NBCCEDP)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chagas Disease [Trypanosoma cruzi Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chapare Hemorrhagic Fever (CHHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chest Cold â€” see Bronchitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CHHF (Chapare Hemorrhagic Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chickenpox Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chickenpox [Varicella Disease]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chikungunya Fever (CHIKV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CHIKV (Chikungunya Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Childhood Arthritis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Childhood Injuries');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Childhood Overweight and Obesity');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chlamydia pneumoniae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chlamydia psittaci Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Psittacosis [Chlamydia psittaci Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chlamydia trachomatis Disease â€” see Chlamydia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chlamydia [Chlamydia trachomatis Disease]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cholera [Vibrio cholerae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Disease Indicators (CDI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Disease Prevention');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Fatigue Syndrome â€” see Myalgic Encephalomyelitis/ Chronic Fatigue Syndrome');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Kidney Disease (CKD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Obstructive Pulmonary Disease (COPD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Traumatic Encephalopathy â€” see CTE');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chronic Wasting Disease (CWD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ciguatera Fish Poisoning');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ciguatoxin â€” see Marine Toxins');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CJD, Classic (Classic Creutzfeldt-Jakob Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CKD (Chronic Kidney Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CKD (Kidney Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Classic Creutzfeldt-Jakob Disease (CJD, Classic)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clonorchiasis â€” see Clonorchis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clonorchis Infection [Clonorchiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clostridium botulinum Infection â€” see Botulism');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clostridium difficile Infection â€” see C. diff. Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clostridium perfringens infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clostridium tetani Infection â€” see Tetanus Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Clotting Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CMV (Cytomegalovirus Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Coal Workers Pneumoconioses');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Coccidioidomycosis â€” see Valley Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cold, Common');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Colorado Tick Fever (CTF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Colorectal (Colon) Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Colorectal Cancer Control Program (CRCCP)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Colorectal Cancer and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Genetics and Genomics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Common Cold');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Concussion ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Congenital Hearing Loss â€” see Hearing Loss in Children');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Congenital Heart Defects');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Screening for Critical Congenital Heart Defects');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Conjunctivitis ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cooleys Anemia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('COPD (Chronic Obstructive Pulmonary Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Coronavirus Disease 2019 [COVID-19]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Corynebacterium diphtheriae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Corynebacterium diphtheria Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Diphtheria [Corynebacterium diphtheriae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('COVID-19 â€” see Coronavirus Disease 2019');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Coxiella burnetii Infection â€” see Q Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CRE (Carbapenem-resistant Enterobacterales)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Creutzfeldt-Jakob Disease, Classic â€” see Classic Creutzfeldt-Jakob Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CRKP (Carbapenem resistant Klebsiella pneumonia )');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Crohnâ€™s Disease â€” see Inflammatory Bowel Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cronobacter Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cryptococcosis, C. gattii. â€” see C. gattii cryptococcosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cryptococcosis, C. neoformans â€” see C. neoformans cryptococcosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cryptosporidiosis â€” see Cryptosporidium Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cryptosporidium Infection [Cryptosporidiosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CTE [Chronic Traumatic Encephalopathy]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Traumatic Brain Injury (TBI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CTF (Colorado Tick Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('CWD (Chronic Wasting Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('cyanobacterial algal bloom-associated illness â€” see Harmful Algal Bloom (HAB)-Associated Illness');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cyclospora Infection [Cyclosporiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cyclosporiasis â€” see Cyclospora Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cysticercosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cystoisospora Infection [Cystoisosporiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cystoisosporiasis â€” see Cystoisospora Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cytomegalovirus Infection (CMV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Death, Leading Causes of Death in Males');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Deep Vein Thrombosis (DVT)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dementia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dengue');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dermatophyte Infection â€” see Ringworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Developmental Disabilities');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diabetes');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dientamoeba fragilis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diet and Nutrition â€” see Nutrition');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diphtheria Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diphtheria [Corynebacterium diphtheriae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diphyllobothriasis â€” see Diphyllobothrium Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Diphyllobothrium Infection [Diphyllobothriasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dipylidium Infection â€” see Tapeworm, Dog and Cat Flea');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dirofilariasis (Dog Heartworm)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Division of Public Health Systems and Workforce Development (DPHSWD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Division of Public Health Systems and Workforce Development (DPHSWD) â€” see Division of Public Health Systems and Workforce Development');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dog Bites');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dog Flea Tapeworm â€” see Tapeworm, Dog and Cat Flea');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dog Heartworm â€” see Dirofilariasis (Dog Heartworm)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dogs, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Down Syndrome [Trisomy 21]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('DPHSWD (Division of Public Health Systems and Workforce Development)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dracunculiasis â€” see Guinea Worm Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Drug Resistance â€” see Antibiotic and Antimicrobial Resistance');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('DVT (Deep Vein Thrombosis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Dwarf Tapeworm [Hymenolepis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('E. coli Infection [Escherichia coli Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ear Infection [Otitis Media]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Early Hearing Detection and Intervention (EHDI) â€” see Hearing, Early Detection & Intervention');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Eastern Equine Encephalitis (EEE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ebola Virus Disease (EVD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('EBV Infection (Epstein-Barr Virus Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Echinococcosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('EEE (Eastern Equine Encephalitis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('EHDI (Early Hearing Detection and Intervention)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ehrlichiosis, Human');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Elephantiasis see Lymphatic Filariasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Elizabethkingia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Emerging Infectious Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Endophthalmitis, Fungal see Fungal Eye Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Entamoeba histolytica infection Amebiasis, Intestinal');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Enteric Diseases from Animals Gastrointestinal Diseases from Animals');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Enterobius vermicularis Infection see Pinworm Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Enterovirus D68');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Enterovirus Infections (Non-Polio) see Non-Polio Enterovirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Epidemic Typhus see Typhus Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Epilepsy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Epstein-Barr Virus Infection (EBV Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ergonomic and Musculoskeletal Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Escherichia coli Infectiosee E. coli Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Esophageal Candidiasis see Thrush');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('EV-D68 see Enterovirus D68');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('EVD (Ebola Virus Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Exserohilum rostratum (Other Pathogenic Fungi)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Fungal diseases [Mycotic diseases]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Extensively Drug-Resistant TB (XDR TB)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Extreme Cold [Hypothermia]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Extreme Heat [Hyperthermia]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Falls, Older Adults');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Falls from Elevation');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Family Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Family Health History');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Family Health History and Breast and Ovarian Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Farm Animals, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Farm Worker Injuries');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cost-effective Rollover Protective Structures (CROPS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fasciitis, Necrotizing see Group A Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fasciola Infection [Fascioliasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fascioliasis see Fasciola Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fasciolopsiasis see Fasciolopsis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fasciolopsis Infection [Fasciolopsiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fetal Alcohol Spectrum Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('FETP see Field Epidemiology Training Program');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('FETP (Field Epidemiology Training Program)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fibromyalgia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Field Epidemiology Training Program (FETP)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fifth Disease [Parvovirus B19 Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Filariasis, Lymphatic see Lymphatic Filariasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Filovirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fish and Amphibians, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flavivirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flavorings-Related Lung Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flea-borne (Murine) Typhus see Typhus Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flu see Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flu, Pandemic see Pandemic Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flu, Seasonal see Seasonal Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flu and Cancer see Cancer and Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Flu Vaccination see Influenza Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Folliculitis â€” see Hot Tub Rash');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Foodborne Illnesses');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fragile X Syndrome (FXS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Francisella tularensis Infection â€” see Tularemia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fungal diseases [Mycotic diseases]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Mold');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fungal Eye Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fungal Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Fungal Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Fungal Pneumonia â€” see Valley Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('FXS (Fragile X Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('GAE (Acanthamoeba) (Granulomatous Amebic Encephalitis (Acanthamoeba))');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('GAE (Granulomatous amebic encephalitis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('GAS (Group A Strep Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gastrointestinal Diseases from Animals [Zoonotic enteric diseases]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('GBS (Group B Strep Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('GDDER (Global Disease Detection and Emergency Response)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Colorectal Cancer â€” see Colorectal Cancer and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Heart Disease â€” see Heart Disease and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Mental Health â€” see Mental Health and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Obesity â€” see Obesity and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Skin Cancer â€” see Skin Cancer and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genetics and Stroke â€” see Stroke and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genital Candidiasis (VVC) [Vulvovaginal Candidiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genital Herpes [Herpes Simplex Virus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genital Warts â€” see Human Papillomavirus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('German Measles (Rubella Virus)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Giardia Infection [Giardiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Giardiasis â€” see Giardia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Glanders [Burkholderia mallei]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Global Disease Detection and Emergency Response (GDDER)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Global Health Security');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Global Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Global Measles Elimination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also G');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Global Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Immunization');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Measles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Measles Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gnathostoma Infection â€” see Gnathostomiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gnathostomiasis [Gnathostoma Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gonorrhea [Neisseria gonorrhoeae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gout');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Granulomatous Amebic Encephalitis (Acanthamoeba) (GAE (Acanthamoeba)) â€” see Acanthamoeba Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Granulomatous amebic encephalitis (GAE) â€” see Balamuthia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Group A Strep Infection (GAS) [Group A Streptococcal Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Group A Streptococcal Infection â€” see Group A Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Group B Strep Infection (GBS) [Group B Streptococcal Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Group B Streptococcal Infection â€” see Group B Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Guillain-BarrÃ© Syndrome');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Guinea Worm Disease [Dracunculiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gynecologic Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Cervical Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ovarian Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Uterine Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vaginal and Vulvar Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('H3N2v influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Variant Viruses - see Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('H5N1 â€” see Avian Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HAB (Harmful Algal Bloom (HAB)-Associated Illness)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Haemophilus influenzae Serotype b â€” see Hib Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hand, Foot, and Mouth Disease (HFMD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hansens Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hantavirus Pulmonary Syndrome (HPS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Harmful Algal Bloom (HAB)-Associated Illness (HAB)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hazardous Drug Exposures in Healthcare');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Head Lice [Pediculus humanus capitis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Healthcare-associated Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Health Disparities in Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Health Disparities in HIV/AIDS, Viral Hepatitis, STDs, and TB');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Health Security â€” see Global Health Security');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Healthy Pets, Healthy People â€” see Animal-Related Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Healthy Weight');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hearing, Early Detection & Intervention');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hearing impairment â€” see Hearing loss, environmental');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hearing loss, environmental [Hearing impairment]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hearing Loss in Children');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heart Disease and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Genetics and Genomics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Heart Disease [Cardiovascular Health]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heart Disease [Cardiovascular Health]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heartland Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heat Stress');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hemoglobinopathies');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hemophilia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hemophilia Treatment Centers (HTC)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hemorrhagic Fevers, Viral â€” see Viral Hemorrhagic Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hendra Virus Disease (HeV Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hepatitis, Viral â€” see Viral Hepatitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hepatitis A Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hepatitis B Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hereditary Bleeding Disorders â€” see Hemophilia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpes, Genital â€” see Genital Herpes');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpes B virus â€” see B virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpes Simplex Virus Infection â€” see Genital Herpes');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpesvirus B â€” see B virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpesvirus simiae â€” see B virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpes Zoster â€” see Shingles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Herpes Zoster Vaccination â€” see Shingles Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heterophyes Infection [Heterophyiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Heterophyiasis â€” see Heterophyes Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HeV Infection (Hendra Virus Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HFMD (Hand, Foot, and Mouth Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hib Infection [Haemophilus influenzae Serotype b]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hib Vaccine (Haemophilus influenzae Serotype b Vaccination)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('High Blood Pressure');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Histoplasma capsulatum Infection [Histoplasmosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Histoplasmosis â€” see Histoplasma capsulatum Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HIV');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HIV/AIDS â€” see HIV');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HIV/AIDS and STDs');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hookworm, Human â€” see Human Hookworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hookworm, Zoonotic â€” see Zoonotic Hookworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Horses, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hot Tub Rash [Pseudomonas dermatitis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HPIV (Human Parainfluenza Viruses)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HPS (Hantavirus Pulmonary Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HPV-Associated Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HPV Infection (Human Papillomavirus Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HPV Vaccination (Human Papillomavirus Vaccination)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('HTC (Hemophilia Treatment Centers)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Ehrlichiosis â€” see Ehrlichiosis, Human');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Hookworm [Ancylostoma duodenale Infection, Necator americanus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Immunodeficiency Virus â€” see HIV');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Papillomavirus Infection (HPV Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Papillomavirus Vaccination (HPV Vaccination)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Parainfluenza Viruses (HPIV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hymenolepis Infection â€” see Dwarf Tapeworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hypertension â€” see High Blood Pressure');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hyperthermia â€” see Extreme Heat');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hypothermia â€” see Extreme Cold');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('IBD (Inflammatory Bowel Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('IMMPaCt (International Micronutrient Malnutrition Prevention and Control Program) â€” see Micronutrient Malnutrition');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Impetigo â€” see Group A Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Infectious Mononucleosis â€” see Epstein-Barr Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Infertility');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Inflammatory Bowel Disease (IBD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('H1N1 Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('People at High Risk');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Seasonal Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Swine Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza, Avian â€” see Avian Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza, Pandemic â€” see Pandemic Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza, Variant');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza and Cancer â€” see Cancer and Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza in Pigs â€” see Swine Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Influenza Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Injury, Healthy Swimming and Recreational Water');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('International Micronutrient Malnutrition Prevention & Control Program (IMMPaCt) â€” see Micronutrient Malnutrition');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Intestinal Amebae Infection, Nonpathogenic â€” see Nonpathogenic (Harmless) Intestinal Protozoa');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Invasive Candidiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Isospora Infection â€” see Cystoisospora Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Jamestown Canyon Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Japanese Encephalitis (JE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Japanese Encephalitis (JE) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Jaundice â€” see Newborn Jaundice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('JE (Japanese Encephalitis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('JE (Japanese Encephalitis) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('K. pneumoniae (Klebsiella pneumoniae)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kala-Azar â€” see Leishmania Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kawasaki Disease (KD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kawasaki Syndrome â€” see Kawasaki Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('KD (Kawasaki Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Keratitis, Acanthamoeba â€” see Acanthamoeba Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Keratitis, Fungal â€” see Fungal Eye Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kernicterus â€” see Newborn Jaundice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('KFD (Kyasanur Forest disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kidney Disease (CKD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Klebsiella pneumoniae (K. pneumoniae)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kyasanur Forest disease (KFD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('LAC (La Crosse Encephalitis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('La Crosse Encephalitis (LAC)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('La Crosse Encephalitis virus (LACV) â€” see La Crosse Encephalitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('LACV (La Crosse Encephalitis virus)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lassa Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Latex Allergies');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('LBRF (Relapsing Fever, Louse-borne)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('LCM (Lymphocytic Choriomeningitis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lead Poisoning');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Legionellosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Legionnaires');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Leishmania Infection [Leishmaniasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Leishmaniasis see Leishmania Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Leprosy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Leptospira Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Leptospirosis see Leptospira Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lice (Body Lice)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lice (Head Lice)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lice (Pubic Lice)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Listeria Infection [Listeriosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Listeriosis ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Liver Disease and Hepatitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Loa loa Infection ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lockjaw â€” see Tetanus Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lockjaw Vaccination â€” see Tetanus (Lockjaw) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Loiasis [Loa loa Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lou Gehrigs Disease see ALS');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Louse-borne Relapsing Fever â€” see Relapsing Fever, Louse-borne');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('LUHF (Lujo Hemorrhagic Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lujo Hemorrhagic Fever (LUHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lung Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lupus (SLE) [Systemic lupus erythematosus]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lyme Disease [Borrelia burgdorferi Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lymphatic Filariasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lymphedema â€” see Lymphatic Filariasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lymphocytic Choriomeningitis (LCM)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MAC (Mycobacterium avium Complex)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mad Cow Disease (BSE) â€” see Bovine Spongiform Encephalopathy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Malaria');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Marburg Hemorrhagic Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Marine Toxins');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MD (Muscular Dystrophy)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MDR TB (Multidrug-Resistant TB)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('ME/CFS (Myalgic Encephalomyelitis/ Chronic Fatigue Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Measles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Measles Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Melioidosis [Burkholderia pseudomallei Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Meningococcal Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Meningococcal Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mental Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mental Health and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Genetics and Genomics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Mental Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mental Retardation');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MERS-CoV (Middle East Respiratory Syndrome Coronavirus)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Methicillin Resistant Staphylococcus aureus â€” see MRSA');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('microalgal bloom-associated illness â€” see Harmful Algal Bloom (HAB)-Associated Illness');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Microcephaly');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Zika Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Zika Virus Infection and Pregnancy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Micronutrient Malnutrition');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Microsporidia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Middle East Respiratory Syndrome Coronavirus (MERS-CoV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Coronavirus (CoV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MMR Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Molluscum Contagiosum');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Monkey B virus â€” see B virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Monkeypox');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mononucleosis, Infectious â€” see Epstein-Barr Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Motor Vehicle Injuries');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mouse and Rat Control â€” see Rodents, Diseases from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('MRSA [Methicillin Resistant Staphylococcus aureus]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mucormycosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mucus â€” see Cold, Common');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Multidrug-Resistant TB (MDR TB)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Multiple organ dysfunction syndrome â€” see Sepsis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mumps');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mumps Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Murine (Flea-borne) Typhus â€” see Typhus Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Muscular Dystrophy (MD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Musculoskeletal Disorders â€” see Ergonomic and Musculoskeletal Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Myalgic Encephalomyelitis/ Chronic Fatigue Syndrome (ME/CFS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mycobacterium abscessus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mycobacterium avium Complex (MAC)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mycobacterium tuberculosis Infection â€” see Tuberculosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mycoplasma pneumoniae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Mycotic diseases â€” see Fungal diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Myelomeningocele â€” see Spina Bifida');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Myiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Naegleria Infection [Primary Amebic Meningoencephalitis (PAM)]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Nairovirus Infection â€” see Crimean-Congo hemorrhagic fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('National Amyotrophic Lateral Sclerosis (ALS) Registry â€” see ALS');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Necrotizing Fasciitis â€” see Group A Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Neglected Tropical Diseases (NTD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Neisseria gonorrhoeae Infection â€” see Gonorrhea');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Neurocysticercosis â€” see Cysticercosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Newborn Hearing â€” see Hearing, Early Detection & Intervention');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Newborn Jaundice [Kernicterus]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Nocardia asteroides Infection â€” see Nocardiosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Nocardiosis [Nocardia asteroides Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('noise, environmental â€” see Hearing loss, environmental');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('noise, recreational â€” see Hearing loss, environmental');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('noise exposure â€” see Hearing loss, environmental');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Non-Polio Enterovirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Nonpathogenic (Harmless) Intestinal Protozoa');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Norovirus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Norwalk-like Viruses (NLV) â€” see Norovirus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Novel Coronavirus [2019-nCoV]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('NTD (Neglected Tropical Diseases)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Nutrition');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('OA (Osteoarthritis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Obesity and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Obesity and Overweight');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Obesity and Overweight, Childhood â€” see Childhood Overweight and Obesity');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Occupational Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Occupational Skin Conditions â€” see Skin Conditions, Occupational');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Occupational Stress â€” see Stress, Occupational');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('OHF (Omsk hemorrhagic fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Omsk hemorrhagic fever (OHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Onchocerciasis â€” see River Blindness');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Opisthorchis Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Oral Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Orf Virus Infection â€” see Sore Mouth Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Oropharyngeal Candidiasis â€” see Thrush');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Osteoarthritis (OA)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Otitis Media â€” see Ear Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Outbreaks');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ovarian and Breast Cancer and Family Health History â€” see Breast and Ovarian Cancer and Family Health History');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ovarian Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Overweight and Obesity â€” see Obesity and Overweight');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Overweight and Obesity, Childhood â€” see Childhood Overweight and Obesity');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PAD (Peripheral Arterial Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pandemic Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Paragonimiasis â€” see Paragonimus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Paragonimus Infection [Paragonimiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Parainfluenza â€” see Human Parainfluenza Viruses');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Parasitic Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Parvovirus B19 Infection â€” see Fifth Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PCP (Pneumocystis pneumonia)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PCV (Pneumococcal Conjugate Vaccine)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PE (Pulmonary Embolism)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pedestrian Injury');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pediculus humanus capitis â€” see Head Lice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pediculus humanus corporis â€” see Body Lice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pelvic Inflammatory Disease (PID)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('People at High Risk');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Peripheral Arterial Disease (PAD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Peripheral Arterial Insufficiency â€” see Peripheral Arterial Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Peripheral Arterial Occlusive Disease â€” see Peripheral Arterial Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Peripheral Vascular Disease â€” see Peripheral Arterial Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pertussis (Whooping Cough)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pertussis (Whooping Cough) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pet-Related Diseases â€” see Animal-Related Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Phthiriasis â€” see Pubic Lice');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PID (Pelvic Inflammatory Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pigs, Influenza in â€” see Swine Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pink Eye [Conjunctivitis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pinworm Infection [Enterobius vermicularis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Plague [Yersinia pestis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumococcal Conjugate Vaccine (PCV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumococcal Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumococcal Polysaccharide Vaccine (PPV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumoconioses, Coal Workers â€” see Black Lung');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumocystis carinii Pneumonia (PCP) Infection â€” see Pneumocystis pneumonia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii) â€” see Pneumocystis pneumonia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumocystis pneumonia (PCP) [Pneumocystis jirovecii pneumonia (previously Pneumocystis carinii)]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pneumonia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Polio Infection [Poliomyelitis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Poliomyelitis Infection â€” see Polio Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Poliomyelitis Vaccination â€” see Polio Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Polio Vaccination [Poliomyelitis Vaccination]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pontiac Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Powassan (POW) virus');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Poxvirus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('PPV (Pneumococcal Polysaccharide Vaccine)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pregnancy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Primary Amebic Meningoencephalitis (PAM) â€” see Naegleria Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Prion Diseases (TSEs) [Transmissible spongiform encephalopathies]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Prostate Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pseudomonas aeruginosa Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pseudomonas dermatitis Infection â€” see Hot Tub Rash');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Psittacosis [Chlamydia psittaci Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Psoriasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pubic Lice [Phthiriasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pulmonary Embolism (PE) â€” see Deep Vein Thrombosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pulmonary Hypertension');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Q Fever [Coxiella burnetii Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RA (Rheumatoid Arthritis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rabies');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rabies Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Raccoon Roundworm Infection [Baylisascaris Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rat-Bite Fever (RBF) [Streptobacillus moniliformis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RBF (Rat-Bite Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Recalled Vaccines');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Recreational Water Illnesses (RWI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Relapsing Fever, Louse-borne (LBRF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Relapsing Fever, Tick-borne (TBRF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Reptiles, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Respiratory Syncytial Virus Infection (RSV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rheumatoid Arthritis (RA)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rickettsia, Spotted Fever Group â€” see Spotted Fever Group Rickettsia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rickettsial Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rickettsia rickettsii Infection â€” see Rocky Mountain Spotted Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rift Valley Fever (RVF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ringworm from Animals');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ringworm [Dermatophyte Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('River Blindness [Onchocerciasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RMSF (Rocky Mountain Spotted Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rodent Control â€” see Rodents, Diseases from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rodents â€” see Rat-Bite Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rodents, Diseases from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rotavirus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rotavirus Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RSV (Respiratory Syncytial Virus Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rubella (German Measles) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rubeola â€” see Measles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Runny Nose â€” see Cold, Common');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RVF (Rift Valley Fever)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('RWI (Recreational Water Illnesses)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Salmonella Infection from Animals');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Salmonella Infection [Salmonellosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Salmonella typhi infection â€” see Typhoid Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Salmonellosis â€” see Salmonella Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Salt');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Heart Disease [Cardiovascular Health]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also High Blood Pressure');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sappinia diploidea and Sappinia pedata â€” see Sappinia Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sappinia Infection [Sappinia diploidea and Sappinia pedata]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('SARS [Severe Acute Respiratory Syndrome]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Scabies');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Scarlet Fever [Group A Strep Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Schistosoma Infection â€” see Schistosomiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Schistosomiasis [Schistosoma Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Screening for Critical Congenital Heart Defects');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Scrub Typhus â€” see Typhus Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Seasonal Flu');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Seizure disorder');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Epilepsy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sepsis [Septicemia]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Septicemia â€” see Sepsis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Septic shock â€” see Sepsis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Severe Acute Respiratory Syndrome â€” see SARS');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sexually Transmitted Diseases (STDs)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Bacterial Vaginosis (BV)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chlamydia [Chlamydia trachomatis Disease]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Genital Herpes [Herpes Simplex Virus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Gonorrhea [Neisseria gonorrhoeae Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Human Papillomavirus Infection (HPV Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Pelvic Inflammatory Disease (PID)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Syphilis [Treponema pallidum Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trichomoniasis [Trichomonas Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sexually Transmitted Disease Surveillance Reports');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('SFGR (Spotted Fever Group Rickettsia)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Shiga toxin-producing E. coli (STEC) â€” see E. coli Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Shigella Infection [Shigellosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Shigellosis â€” see Shigella Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Shingles Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Shingles [Varicella Zoster Virus (VZV)]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sickle Cell Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('SIDS (Sudden Infant Death Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sinus Infection [Sinusitus]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sinusitus â€” see Sinus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Skin Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Skin Cancer and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Genetics and Genomics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also S');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Skin Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Skin Conditions, Occupational');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('SLE (Lupus)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sleep and Sleep Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sleeping Sickness [African Trypanosomiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Smallpox');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Smoking and Tobacco Use');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sodium â€” see Salt');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Soil Transmitted Helminths');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sore Mouth Infection [Orf Virus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sore Throat');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Southern Tick-Associated Rash Illness (STARI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Spina Bifida [Myelomeningocele]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Spirillum minus Infection â€” see Rat-Bite Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sporothrix schenckii infection â€” see Sporotrichosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sporotrichosis [Sporothrix schenckii infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Spotted Fever Group Rickettsia (SFGR)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Staph â€” see Staphylococcus aureus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Staphylococcus aureus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('STARI (Southern Tick-Associated Rash Illness)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('STDs (Sexually Transmitted Diseases)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('STDs and HIV/AIDS â€” see HIV/AIDS and STDs');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('STEC (Shiga toxin-producing E. coli)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Strep Infection, Group A â€” see Group A Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Strep Infection, Group B â€” see Group B Strep Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Strep Throat [Group A Strep Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Streptobacillus moniliformis Infection â€” see Rat-Bite Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Streptococcus pneumoniae Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Stress, Occupational');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Stroke');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Stroke and Genetics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Genetics and Genomics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Stroke');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Strongyloidiasis â€” see Strongyloidiasis - see Strongyloides Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Strongyloidiasis - see Strongyloides Infection [Strongyloidiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Sudden Infant Death Syndrome (SIDS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Surveillance Reports, Sexually Transmitted Disease â€” see Sexually Transmitted Disease Surveillance Reports');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Swimmers Itch [Cercarial Dermatitis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Swimming-related Illness â€” see Recreational Water Illnesses');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Swine Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Symptom Relief for Upper Respiratory Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Syphilis [Treponema pallidum Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Systemic lupus erythematosus â€” see Lupus');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Taenia Infection â€” see Tapeworm Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tapeworm, Dog and Cat Flea [Dipylidium Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tapeworm Infection [Taenia Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB (Tuberculosis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB (Tuberculosis) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB and HIV Coinfection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB and the African-American Communtiy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB Data & Statistics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB Education and Training Network');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TBI (Traumatic Brain Injury)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB in African-Americans â€” see TB and the African-American Communtiy');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TBRF (Relapsing Fever, Tick-borne)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB Surveillance Reports â€” see TB Data & Statistics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TB Testing & Diagnosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Testicular Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tetanus (Lockjaw) Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tetanus (Lockjaw) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tetanus Disease [Clostridium tetani Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Thalassemia');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Thoracic Aortic Aneurysm â€” see Aortic Aneurysm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Throat, Sore â€” see Sore Throat');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Throat, Strep [Group A Strep Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Thrombophilia â€” see Clotting Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Thrombosis â€” see Clotting Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Thrush [Oropharyngeal Candidiasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tick-borne Relapsing Fever â€” see Relapsing Fever, Tick-borne');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tickborne Diseases â€” see Ticks');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ticks');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Anaplasmosis, Human');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Babesiosis [Babesia Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ehrlichiosis, Human');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lyme Disease [Borrelia burgdorferi Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Powassan (POW) virus');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Relapsing Fever, Tick-borne (TBRF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rocky Mountain Spotted Fever (RMSF) [Rickettsia rickettsii Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Southern Tick-Associated Rash Illness (STARI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tularemia [Francisella tularensis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Ticks');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tinea â€” see Ringworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tobacco Use, Smoking and â€” see Smoking and Tobacco Use');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tourette Syndrome (TS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Toxocara Infection â€” see Toxocariasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Toxocariasis [Toxocara Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Toxoplasma Infection â€” see Toxoplasmosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Toxoplasmosis [Toxoplasma Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trachoma Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Transmissible spongiform encephalopathies â€” see Prion Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Traumatic Brain Injury (TBI)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Traumatic Occupational Injuries');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trench Fever â€” see Bartonella Quintana Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Treponema pallidum Infection â€” see Syphilis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trichinellosis (Trichinosis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trichomonas Infection â€” see Trichomoniasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trichomoniasis [Trichomonas Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trichuriasis â€” see Whipworm Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trisomy 21 â€” see Down Syndrome');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trypanosoma cruzi Infection â€” see Chagas Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Trypanosomiasis, African â€” see Sleeping Sickness');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TS (Tourette Syndrome)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('TSEs (Prion Diseases)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis (TB) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis (TB) [Mycobacterium tuberculosis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis and HIV Coinfection â€” see TB and HIV Coinfection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis Skin Test â€” see TB Testing & Diagnosis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis Training â€” see TB Education and Training Network');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tuberculosis Vaccine (BCG)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Tularemia [Francisella tularensis Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Ticks');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Typhoid Fever Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Typhoid Fever [Salmonella typhi infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Typhus Fevers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ulcerative Colitis â€” see Inflammatory Bowel Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Undulant Fever â€” see Brucella Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Unexplained Respiratory Disease Outbreaks (URDO)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Universal Newborn Hearing Screening â€” see Hearing, Early Detection & Intervention');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Upper Respiratory Infection Symptom Relief â€” see Symptom Relief for Upper Respiratory Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('URDO (Unexplained Respiratory Disease Outbreaks)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Uterine Cancer');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vaccination, American Indian and Alaska Native â€” see American Indian and Alaska Native Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vaginal and Vulvar Cancers');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vaginal Candidiasis â€” see Genital Candidiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Valley Fever [Coccidioidomycosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vancomycin-Intermediate/Resistant Staphylococcus aureus Infections [VISA/VRSA]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vancomycin-resistant Enterococci Infection (VRE)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Variant Creutzfeldt-Jakob Disease (vCJD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Variant Viruses - see Influenza');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Varicella-Zoster Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Varicella Disease â€” see Chickenpox');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Varicella Vaccination â€” see Chickenpox Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Varicella Zoster Virus (VZV) â€” see Shingles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Variola Major Virus Infection â€” see Smallpox');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Variola Minor Virus Infection â€” see Smallpox');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('vCJD (Variant Creutzfeldt-Jakob Disease)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vector-borne Diseases');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VHF (Viral Hemorrhagic Fevers)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vibrio cholerae Infection â€” see Cholera');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vibrio Illness [Vibriosis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vibriosis â€” see Vibrio Illness');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Viral Hemorrhagic Fevers (VHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Alkhurma hemorrhagic fever (AHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Chapare Hemorrhagic Fever (CHHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Crimean-Congo hemorrhagic fever (CCHF) [Nairovirus Infection]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Ebola Virus Disease (EVD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Hantavirus Pulmonary Syndrome (HPS)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Kyasanur Forest disease (KFD)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lassa Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Lujo Hemorrhagic Fever (LUHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Marburg Hemorrhagic Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Omsk hemorrhagic fever (OHF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Rift Valley Fever (RVF)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Viral Hepatitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Viral Meningitis [Aseptic Meningitis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('see also Meningitis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VISA/VRSA â€” see Vancomycin-Intermediate/Resistant Staphylococcus aureus Infections');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vision Impairment');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Von Willebrand Disease â€” see VWD');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VRE (Vancomycin-resistant Enterococci Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Vulvovaginal Candidiasis â€” see Genital Candidiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VVC (Genital Candidiasis)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VWD [Von Willebrand Disease]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('VZV (Varicella Zoster Virus) â€” see Shingles');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Water-related Topics');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Weight, Healthy â€” see Healthy Weight');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('West Nile Virus Infection (WNV Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Whipworm Infection [Trichuriasis]');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Whitmore Disease');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Whooping Cough');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Whooping Cough (Pertussis) Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Wildlife, Infections from');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Winter Storms â€” see Extreme Cold');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('WNV Infection (West Nile Virus Infection)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Women Bleeding Disorders');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Women Health');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('XDR TB (Extensively Drug-Resistant TB)');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yeast Infection â€” see Genital Candidiasis');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yellow Fever');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yellow Fever Vaccination');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yersinia enterocolitica Infection ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yersinia pestis Infection ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Yersiniosis ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zika Virus Infection');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zoonotic Diseases from Animals ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zoonotic enteric diseases ');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zoonotic Hookworm');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zoster');
INSERT INTO DISEASE_DIRECTORY(disease) VALUES('Zygomycosis ');