package ng.com.bitsystems.mis.models.admissions.outpatient;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * OutpatientPrescriptionGeneratedAdminTime generated by hbm2java
 */
import lombok.*;
import ng.com.bitsystems.mis.models.BaseEntity;

import javax.persistence.Entity;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class OutpatientPrescriptionGeneratedAdminTime  extends BaseEntity {

     private OutpatientPrescriptionSchedule outpatientPrescriptionSchedule;
     private Integer extimatedAdminTime;

}


