package ng.com.bitsystems.mis.models;
// Generated Jun 24, 2020 12:32:32 AM by Hibernate Tools 4.3.1


import lombok.*;

import javax.persistence.Entity;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class Users  extends Person {

     private String title;
     private Set donorBleedingSchedules = new HashSet(0);
     private Set patientsMedicalHistories = new HashSet(0);
     private Set laboratoryInvestigationResultVerifieds = new HashSet(0);
     private Set usersPrivileges = new HashSet(0);
     private Set clerkses = new HashSet(0);
     private Set vaccineScheduleses = new HashSet(0);
     private Set laboratoryTransactionDetailses = new HashSet(0);
     private Set diseaseDirectories = new HashSet(0);
     private Set patientsFamilySocialHistories = new HashSet(0);
     private Set requisitionses = new HashSet(0);
     private Set laboratoryCollectedSampleses = new HashSet(0);
     private Set patientsSocialHistories = new HashSet(0);
     private Set laboratoryTransactionPaymentses = new HashSet(0);
     private Set donorDonateds = new HashSet(0);
     private Set laboratoryInvestigationResultCollectionLogses = new HashSet(0);
     private Set donorIssuanceLogses = new HashSet(0);
     private Set pharmacyPrescriptionLogses = new HashSet(0);


}


