package ng.com.bitsystems.mis.models.inventory;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * InventoryPerLaboratoryTransaction generated by hbm2java
 */

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import ng.com.bitsystems.mis.models.BaseEntity;
import ng.com.bitsystems.mis.models.laboratories.LaboratoryInvestigations;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class InventoryPerLaboratoryTransaction  extends BaseEntity {

     @ManyToOne
     @JoinColumn(name = "inventory_id")
     private Inventory inventory;

     @ManyToOne
     @JoinColumn(name = "laboratoryinvestigation_id")
     private LaboratoryInvestigations laboratoryInvestigations;

     private Integer requiredQty;

}


