package ng.com.bitsystems.mis.models.insurance;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * InsuranceBloodbankTransaction generated by hbm2java
 */

import lombok.*;
import ng.com.bitsystems.mis.models.transactions.BloodbankTransactionDetails;

import javax.persistence.Entity;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class InsuranceBloodbankTransaction  extends Insurance {
     private BloodbankTransactionDetails bloodbankTransactionDetails;
}


