package ng.com.bitsystems.mis.models.rewards.promos;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * PharmacyPromoProductRecivedLogs generated by hbm2java
 */

import lombok.*;
import ng.com.bitsystems.mis.models.BaseEntity;
import ng.com.bitsystems.mis.models.transactions.pharmacy.PharmacyService;

import javax.persistence.Entity;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class PharmacyPromoProductRecivedLogs  extends BaseEntity {


     private PharmacyPromoProductBasedRewards pharmacyPromoProductBasedRewards;
     private PharmacyPromosProducts pharmacyPromosProducts;
     private PharmacyService pharmacyTransactionDetails;


}


