package ng.com.bitsystems.mis.models.referrals;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * PatientsReferrals generated by hbm2java
 */

import lombok.*;
import ng.com.bitsystems.mis.models.Person;
import ng.com.bitsystems.mis.models.patients.Patients;

import javax.persistence.Entity;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class PatientsReferrals  extends Person {


     private int id;
     private Patients patientsByReferredPatient;
     private Patients patientsByReferringPatient;


}


