package ng.com.bitsystems.mis.models.accounts.payments;
// Generated Jul 29, 2020 6:59:27 PM by Hibernate Tools 4.3.1



/**
 * AccountsOtherServiceBillingsPayments generated by hbm2java
 */
import lombok.*;
import ng.com.bitsystems.mis.models.accounts.OtherServices;

import javax.persistence.Entity;


@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class OtherServicePayments extends Payments {
     private OtherServices otherServices;
}


