package ng.com.bitsystems.mis.models.requests;



/**
 * Requests generated by hbm2java
 */

import lombok.*;
import ng.com.bitsystems.mis.models.BaseEntity;

import javax.persistence.Entity;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Entity
public class Requests  extends BaseEntity {

     private String groupName;
     private String item;
     private int quantity;
     private String buyer;
     private String status;

}


